gitbook build assist books/assist
gitbook build es6 tools/es6
gitbook build fis3 tools/fis3
gitbook build koa tools/koa
gitbook build node tools/node
gitbook build react tools/react
gitbook build tools books/tools
gitbook build vue tools/vue
gitbook build vue-router tools/vue-router